openapi: 3.0.0
info:
  title: Hapus data pasien
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: patient_id
    in: path
    description: ID pasien yang akan dihapus
    required: true
    type: integer
responses:
  200:
    description: Data pasien berhasil dihapus
  404:
    description: Data tidak ditemukan