openapi: 3.0.0
info:
  title: Ambil Semua Data Patients
  version: 1.0.0
tags:
  - name: Daftar API
definitions:
  Patients:
    type: object
    properties:
      patient_id:
        type: integer
        description: ID pasien
      name:
        type: string
        description: Nama pasien
      age:
        type: integer
        description: Umur pasien
      medical_history:
        type: string
        description: Riwayat kesehatan pasien
responses:
  200:
    description: Daftar semua pasien
    schema:
      type: array
      items:
        $ref: '#/definitions/Patients'