openapi: 3.0.0
info:
  title: Update data pasien
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: patient_id
    in: path
    descritpion: ID pasien yang akan diperbarui
    required: true
    type: integer
  - in: body
    name: body
    description: Data pasien yang akan diperbarui
    required: true
    scehma:
      $ref: '#/definitions/Patients'
responses:
  200:
    description: Data berhasil diperbarui
    schema:
      $ref: '#/definitions/Patients'
  404:
    description: Data tidak ditemukan